apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-config
  namespace: ns-sigemad
data:
  config.json: |
    {
      "production": true,
      "urlBase": /api/v1,
      "urlGeoserver": https://geoserver.sigemad.duckdns.org/geoserver/sigemad/
    }
