apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32001/sigemad-frontend:develop-22cb2a0e1c846024a6942edfc9be6f471a6fd7e2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: angular-config
