apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-sigemad-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32001/sigemad-frontend:release-fc5795e22bc7c53b25d170d062ed6e572c055bfb
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: angular-config
