apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
  namespace: ns-sigemad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
      - name: geoserver
        image: localhost:32001/geoserver-fontconfig:2.26.2-v4
        ports:
          - containerPort: 8080
        env:
          - name: GEOSERVER_ADMIN_USER
            value: "admin"
          - name: GEOSERVER_ADMIN_PASSWORD
            value: "sigemad"
          - name: PROXY_BASE_URL
            value: "https://geoserver.sigemad.duckdns.org/geoserver"
          - name: INSTALL_EXTENSIONS
            value: "true"
          - name: STABLE_EXTENSIONS
            value: "sqlserver"
          - name: SKIP_DEMO_DATA
            value: "true"
          - name: GEOSERVER_CSRF_DISABLED
            value: "true"
          - name: EXTRA_JAVA_OPTS
            value: "-Dorg.geotools.coverage.jaiext.enabled=true"
          - name: TZ
            value: "Europe/Madrid"
        volumeMounts:
          - name: geoserver-data
            mountPath: /opt/geoserver_data
          - name: geoserver-global-override
            mountPath: /opt/geoserver_data/global.xml
            subPath: global.xml
          - name: geoserver-webxml-cors
            mountPath: /usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
            subPath: web.xml
      volumes:
        - name: geoserver-data
          persistentVolumeClaim:
            claimName: pvc-geoserver
        - name: geoserver-global-override
          configMap:
            name: geoserver-global-cm
        - name: geoserver-webxml-cors
          configMap:
            name: geoserver-webxml-cors
