# 1) Creamos aquí el PVC RWM
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sigemad-backup
  namespace: ns-sigemad-release
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
# 2) Tu StatefulSet, con el volumen de backup añadido
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  namespace: ns-sigemad-release
spec:
  serviceName: sqlserver
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql

        - name: init-backup-dir
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /var/opt/mssql/backup && \
              chown -R 10001:0 /var/opt/mssql/backup
          volumeMounts:
            - name: mssql-backup
              mountPath: /var/opt/mssql/backup

      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
              name: sql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TZ
              value: "Europe/Madrid"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-sqlserver
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
            - name: mssql-backup
              mountPath: /var/opt/mssql/backup

      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: pvc-sqlserver
        - name: mssql-backup
          persistentVolumeClaim:
            claimName: pvc-sigemad-backup
