apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  namespace: ns-sigemad-release
spec:
  serviceName: sqlserver
  replicas: 1

  selector:
    matchLabels:
      app: sqlserver

  template:                      # <— aquí debe ir el PodTemplate
    metadata:
      labels:
        app: sqlserver
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh","-c","chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
              name: sql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: TZ
              value: "Europe/Madrid"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-sqlserver
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: pvc-sqlserver

  updateStrategy:
    type: RollingUpdate
